name: Wrye Bash CI

on: push

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python 2.7
      uses: actions/setup-python@v2
      with:
        python-version: 2.7
        architecture: 'x64'
    - name: Restore dependencies cache
      uses: actions/cache@v1
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install -U pip pipenv
        python -m pipenv sync --dev
    - name: Build Wrye Bash
      # Note the configs - needed for build.py. Also, we don't build the
      # installer on CI, fails with an empty traceback for whatever reason
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email "github-action@users.noreply.github.com"
        python -m pipenv run build --verbose --no-installer
    - name: Test Wrye Bash
      run: |
        python -m pipenv run python -m pytest
